name: Aggiorna Top Languages

on:
  schedule:
    - cron: '0 8 * * *'   # Ogni giorno alle 08:00 UTC
  workflow_dispatch:       # Permette di eseguire manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scarica top-langs.png
        run: |
          mkdir -p assets
          curl -s -o assets/top-langs.png "https://github-readme-stats.vercel.app/api/top-langs/?username=IlGiocatore93&layout=compact&langs_count=8&theme=github_dark&hide_border=true&cache_seconds=1800"

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add assets/top-langs.png
          git commit -m "Aggiorna immagine Top Languages [Automatica]" || echo "Nessuna modifica da commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

